/**
 * PDF Exporter — Generates printable pattern sheets.
 *
 * Uses a simple HTML-to-text approach for MVP. A pdfkit-based
 * implementation can be swapped in later for richer output.
 */

import type { StitchGrid, DmcUsage } from "../../domain/stitch/types";
import { getGridDimensions } from "../../domain/stitch/stitchGrid";

/**
 * Generate a text-based pattern export suitable for printing.
 * Returns a UTF-8 buffer with grid preview, color key, and metadata.
 */
export function generatePatternPDF(
  grid: StitchGrid,
  palette: DmcUsage[],
  metadata: { name: string; gridSize: number; createdAt?: Date },
): Buffer {
  const { width, height } = getGridDimensions(grid);
  const totalStitches = palette.reduce((s, p) => s + p.count, 0);

  let output = "";
  output += "═══════════════════════════════════════════════\n";
  output += "  StitchWise Studio — Pattern Export\n";
  output += "═══════════════════════════════════════════════\n\n";
  output += `  Pattern:        ${metadata.name}\n`;
  output += `  Grid Size:      ${width} × ${height}\n`;
  output += `  Total Stitches: ${totalStitches}\n`;
  output += `  Colors Used:    ${palette.length}\n\n`;

  // Grid preview (ASCII art)
  output += "─── Grid Preview ──────────────────────────────\n";
  const maxPreviewSize = 40;
  const scale = Math.max(1, Math.ceil(Math.max(width, height) / maxPreviewSize));
  for (let r = 0; r < height; r += scale) {
    for (let c = 0; c < width; c += scale) {
      const cell = grid[r]?.[c];
      const color = cell?.color || "#ffffff";
      if (color === "#ffffff" || color === "#fff") {
        output += "·";
      } else {
        output += "█";
      }
    }
    output += "\n";
  }
  output += "  (· = fabric, █ = stitch)\n\n";

  // DMC Color Key
  output += "─── DMC Color Key ─────────────────────────────\n";
  output += `  ${"Code".padEnd(12)} ${"Name".padEnd(25)} ${"Count".padEnd(8)} ${"%"}\n`;
  output += `  ${"-".repeat(52)}\n`;
  for (const color of palette) {
    const pct = totalStitches > 0 ? Math.round((color.count / totalStitches) * 100) : 0;
    output += `  ${color.code.padEnd(12)} ${color.name.padEnd(25)} ${String(color.count).padEnd(8)} ${pct}%\n`;
  }

  output += "\n";
  output += "═══════════════════════════════════════════════\n";
  output += `  Generated by StitchWise Studio\n`;
  output += `  stitchwisestudio.com\n`;
  output += `  ${new Date().toISOString().slice(0, 10)}\n`;
  output += "═══════════════════════════════════════════════\n";

  return Buffer.from(output, "utf-8");
}
